# Generated by Django 3.2 on 2021-04-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='The exact dates of her giveaway won’t be known just year but now through November there will be random giveaways for tickets and prizes.'),
            preserve_default=False,
        ),
    ]
