# Generated by Django 3.2 on 2021-04-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
