# Generated by Django 3.1.7 on 2021-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_show_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
