# Generated by Django 3.2 on 2021-04-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_alter_show_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
