# Generated by Django 3.2 on 2021-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_alter_show_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
