# Generated by Django 3.2 on 2021-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_alter_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
